### ISSUE TITLE
Subtitles takes about two minutes to load

### ISSUE THREAD

**Issue by jcwrh** [tsaridas/stremio-docker#16]
I'm using your docker container and this works great. The only thing is that subtitles won't show up or are available after two minutes, when playing a movie or series episode. Is there something that I can do about this ?

**Comment by jcwrh** [comment]
Okay, thanks for your reply...

**Comment by tsaridas** [comment]
your issue fixed ?

**Comment by jcwrh** [comment]
Not yet, i'm running the container on a raspberry pi 4, could that be the reason, for the subtitles to appear 2 minuten later?
