### ISSUE TITLE
failed to fetch

### ISSUE THREAD

**Issue by MaJoRX0** [tsaridas/stremio-docker#17]
no matter what i do i cant stream any movie I'm accessing the server via a different network and PC I'm hosting the server on a VPS, I made sure to allow all the ports just to check if that gonna solve the issue or not but whenever I try to play something I get the field to fetch error here is what I get in the network tap

![image](https://github.com/tsaridas/stremio-docker/assets/45786523/a309e27b-6ab8-4d59-b84f-47c17ceee330)

from what I've read on the internet about the Mixed block it seems like I need https cer for my sever but didn't see anything about that on this page.

adding to that, accessing the stremio webpage via port 8080 and then adding the server from settings will allow me to play movies but without any video I just hear sounds

**Comment by MaJoRX0** [comment]
from what I've read on the internet about the Mixed block it seems like I need https cer for my sever but didn't see anything about that on this page

**Comment by MaJoRX0** [comment]
adding to that, accessing the stremio webpage via port 8080 and then adding the server from settings will allow me to play movies but without any video I just hear sounds

**Comment by tsaridas** [comment]
Im sorry I have no idea what the problem is exactly with your setup.
