### ISSUE TITLE
Server Url

### ISSUE THREAD

**Issue by joaobosconff** [tsaridas/stremio-docker#18]
First of all, thanks for the wonderful job, i had problems using the oficial stremio-server on a SOC Orange Pi 5 (similar to RPI5) and your solution works flawlessly.

Is it possible to set automatic the streaming server url?

**Comment by tsaridas** [comment]
no way to hardcode server url as far as I know but you could so something else to set it up automatically.

on the container you can setup env variable WEBUI_LOCATION: http://{{ LAN IP }}:8080/shell/

and when you open your browser and point it to the server url http://{{ LAN IP }}:11470 it should redirect you to the web player and setup server automatically. This is assuming you are using http. But even if you do this you would need to login to get your addons and that step I don't know how to automate. Its probably possible though.

Hope that makes sense.
