### ISSUE TITLE
Failure playback youtube video

### ISSUE THREAD

**Issue by glensc** [tsaridas/stremio-docker#22]
Used youtube to test whether this works, and it gave warning in logs and error in player

```
stremio         | WARNING: ytdl-core is out of date! Update with "npm install ytdl-core@latest".
```

The fix was as it old:

```
docker exec -it stremio sh
npm install ytdl-core@latest
```

**Comment by glensc** [comment]
Actually, I'm not sure what's happening. I stopped the container and youtube videos still play.

**Comment by tsaridas** [comment]
which version are you using ? I tried with the latest version to watch a trailer and it works fine. Can you tell me exactly how to reproduce this ?

**Comment by glensc** [comment]
I used your latest image (pulled today) and their website and their app. i don't remember anymore where I played it from. I'm too new (few hours of experience) to understand how this all works.
