### ISSUE TITLE
Nvidia h264_nvenc support

### ISSUE THREAD

**Issue by Owen000** [tsaridas/stremio-docker#23]
I have tried every option I could possibly think of to get hardware acceleration for my RTX1060 to work. I have switched the base image to use the CUDA one from Nvidia. Compiled from source using these flags (and just trying from the toolkit) https://trac.ffmpeg.org/wiki/HWAccelIntro#NVENC additionally I followed all official Nvidia instructions yet I still get the Unknown encoder 'h264_nvenc ffmpeg' error. Any help would be greatly appreciated. Also even without hardware acceleration no Transcode profile is available it default to "Disabled" while using stremio-service I have the option for nvenc-win (i'm not sure but getting hardware acceleration may enable that as an option?)

**Comment by tsaridas** [comment]
Stremio does a test on startup to choose available hardware acceleration profile and if it fails it disables it. 
I don't have an nvidia card so I don't think I'll be much help. What you could do try the official stremio image which only containers the server : https://github.com/Stremio/server-docker. ffmpeg there might be compiled with nvidia codex but I also don't know what exactly one needs to do to present the device inside the container. Maybe you can do some research on that.
