### ISSUE TITLE
Automatic server url connection?

### ISSUE THREAD

**Issue by vijayvcm** [tsaridas/stremio-docker#31]
Hey @tsaridas,

Thanks for making this combined container solution. 

It’s really helpful, particularly for iPhone users like me who can’t stream torrents. I can now host my web and server in the Raspberry Pi and I can stream from my mobile without any Cors/https issues.

one thing I wanted to know, Can we not configure the server IP address automatically? By default it is always 127.0.0.1

When I use it on my home network it's 192.168.*.* again when I switch to its VPN network it's 10.140.*.* and for the public its random IP address.

Is there any way we can configure the container so that it can automatically pick up the IP and resolve it based on the network we are in?

**Comment by tsaridas** [comment]
hi, i think you can setup the streaming server on the url but never tried it. 

something like : 192.168.1.10:8080/?streamingServer=https%3A%2F%2F141-147-106-94.519b6502d940.stremio.rocks%3A12470

you can ask for support in discord. maybe someone there might help or look at the web version repo to check the code.

happy to add it to the documentation if you figure it out.

**Comment by jumpnkick** [comment]
Hey there! Thanks a lot for this solution. I'm trying to build an UmbrelOS app (a webui based OS built on dockerized apps) an this client/server solution is exactly what I'm looking for.

It worked just fine in my RPI 4 (probably will not be able to transcode many stuff, but it worked great). 
The only thing I couldn´t get to work is login with facebook (and I don´t understand why in new accounts I cannot find tpb addon, and torrentio addon just gives me random results, but in my old facebook logged account everything is there and works fine).

If ever get to publish the app on umbrel, all the credits will be for you!

Thanks a lot!

**Comment by jumpnkick** [comment]
Oh! And one more question? Should I be able to cast to a Chromecast as is?
I didn't disable casting when running the container but casting option is greyed in the player.

**Comment by vijayvcm** [comment]
> hi, i think you can setup the streaming server on the url but never tried it.
> 
> something like : 192.168.1.10:8080/?streamingServer=http%3A%2F%2F192.168.1.10%3A11470
> 
> you can ask for support in discord. maybe someone there might help or look at the web version repo to check the code.
> 
> happy to add it to the documentation if you figure it out.
> 
> i have the same setup as you and because im logged in on my iphone for example i dont need to setup the server every time. same for other devices.

@tsaridas Thanks. It worked when I used the URL you mentioned above. It automatically sets the server URL.

However, I don’t want to bookmark the URL for different networks on different devices. I am looking for something like a localhost/127.0.0.1 which will automatically establish a connection. 

I am not much familiar with the docker and how the services communicating internally.

**Comment by vijayvcm** [comment]
I thought localhost will automatically work since both are in the same docker container.

**Comment by tsaridas** [comment]
what I did is have an nginx open at port 80 and have the links from all the services I run. maybe you can also specify WEBUI_LOCATION to your webplayer and logically it should automatically setup the server by pointing to the server's port instead of 8080.
