### ISSUE TITLE
more than one Docker.

### ISSUE THREAD

**Issue by Danielbcvv** [tsaridas/stremio-docker#32]
I am a layperson in this. How do I change the ports? I want to create more than one different Docker. I tried to change it in the .yaml, but the web UI would not open.

**Comment by Danielbcvv** [comment]
I need to create more than one access in Streamio and I was thinking of creating Docker containers with different ports or trying some other way, but I don't know how

**Comment by Danielbcvv** [comment]
I managed to make it work, I just have one question: the download traffic of the videos will go to the server and then be transmitted from the server to the user, correct? I want to know because I want to centralize the use of Streamio on the server so that my girlfriend and I can use Streamio with Real-Debrid even when we are outside the house, since there is the limitation of using it on only one router IP at a time.

**Comment by tsaridas** [comment]
downloading is done on the server and server transmits to the client. client doesn't do any downloading.
