### ISSUE TITLE
Facebook login and Casting

### ISSUE THREAD

**Issue by jumpnkick** [tsaridas/stremio-docker#33]
It was great to come accross yout stremio docker server/client. I've been trying for a while to make Stremio available for UmbrelOS, but not having a server/client running all in one container defeated the cause of having Stremio running on a home server.
Thanks a lot!
That being said, wanted to address this to issues which I would like to overcome to be able to streamline this for Umbrel OS (all the credits will be given to you, I just want this tool to be available for Umbrel users).
The client/server works like a charm in my RPI 4 (kind of standard HW for UmbrelOS, excluding their own developed HW).
The only two features that wouldn't work are FB login and Casting to a device.
FB login throws the following error: JSSDK unknown host domain
The domain where you host the Facebook SDK for Javascript is in your app's Javascript SDK host domain list. Specify your host domain in the login settings in the app dashboard.
I believe it might have to do with the fact I'm accessing http webui and not https (for Umbrel porpose, https is not an option, that is why I want it to work on http, if that is the problem, and is actually possible). 
On casting to a device, I haven't disabled in the options it when running the container, but still in the player the button is greyed out (I have a running chromecast on my network), so I assumed it is disabled by default, or simply not working.
Any help with this issues or at least the reasons for them would be awesome.
In any case, great job and thanks once again!

**Comment by jumpnkick** [comment]
Thanks for the answer!
I'm working on it. As soon as I have news, I'll be back with an update.

**Comment by jumpnkick** [comment]
I know now by stremio devs, that the reason FB login doesn't work is because there are just a bunch of domains authorized by them to do so.
One of them being app.strem.io. The problem is that app.strem.io is pointed to servers stremio (11470), and not the client's (8080).
I think a workaround could be to actually point app.strem.io to port 8080 (if that is actually possible...).
I'm really new at this. If you know this is possible, or at least where should I be looking at this in your image, it would be awesome.
Thanks!

**Comment by tsaridas** [comment]
I belive you can change that by setting 👍 

WEBUI_LOCATION | - | http://192.168.1.10:8080 | Sets the redirect page for web player and automatically sets up streaming server for you when one tries to access server at port 11470 or 12470. Default is https://app.strem.io/shell-v4.4/
-- | -- | -- | --
