### ISSUE TITLE
Stream is not supported

### ISSUE THREAD

**Issue by newhopespace** [tsaridas/stremio-docker#37]
![image](https://github.com/user-attachments/assets/4599e5fd-013d-41fb-aba8-09838e919574)
Using http only on a local container.
I've tried with different browsers with the same result.
The machine where Docker is running is a VM over Proxmox, and no GPU passtrough.
I also have Jellyfin running on another containr and it works well with no GPU hardware.
Do I need GPU hardware to stream?

**Comment by newhopespace** [comment]
I thought that anyone could access stremio web and play content, but it seems that you need an app companion to play content? I guess this solves the issue, but not what I wanted: https://blog.stremio.com/using-stremio-service/

**Comment by TheGlitch1** [comment]
Hi, 
In the settings you should be able to find steaming options , in the URL option write your address:11470 

Once you will confirm this url , you will status option, press reload and now you have your streaming player up.

**Comment by newhopespace** [comment]
That port is loading a stremio version that's not on my LAN. What is that? I just want it to run on a local container on my LAN.

**Comment by tsaridas** [comment]
when you open the web application on localaddress:8080 you need to go to settings (left menu) -> Streaming -> Configure Server Url button 
and set the server url to http://YourLocalAddress:11470

**Comment by newhopespace** [comment]
> when you open the web application on localaddress:8080 you need to go to settings (left menu) -> Streaming -> Configure Server Url button and set the server url to http://YourLocalAddress:11470

It is working as intended now! Thanks for the hint!
