### ISSUE TITLE
server seems to die without logs

### ISSUE THREAD

**Issue by utkarshsethi** [tsaridas/stremio-docker#38]
Not sure how to verify this as the webapp seems to keep running but the stremio-server parts seems to die without any error in the container logs.

https://*.519b6502d940.stremio.rocks:8080 is still working but says server offline

https://*.519b6502d940.stremio.rocks:12470 doesn't work

I've also tried with https://localhost:11470 seems to keep dying.

restarting the container makes it work for a minute but then it is unreachable again.

**Comment by tsaridas** [comment]
which version of the container are you using ? can you post logs ?

**Comment by Xpiravit** [comment]
I am having the exact same problem, although I opted for the simple configuration with http on local ip. Below you can find my logs and yaml file.
[_streamio-docker-stremio-1_logs.txt](https://github.com/user-attachments/files/16786114/_streamio-docker-stremio-1_logs.txt)
[docker-compose.txt](https://github.com/user-attachments/files/16786163/docker-compose.txt)

**Comment by tsaridas** [comment]
check https://github.com/tsaridas/stremio-docker/issues/40

**Comment by utkarshsethi** [comment]
> which version of the container are you using ? can you post logs ?

I'm on the `:latest`, and it doesn't seem to have occurred in the last few days, maybe something fixed in the last release? I see the image was updated 8 days ago.

But the last time I had the issue, I remember checking the logs and having no errors/warnings of any sort.

**Comment by utkarshsethi** [comment]
> which version of the container are you using ? can you post logs ?

I'm on the `:latest`, and it doesn't seem to have occurred in the last few days (also haven't really used it), maybe something fixed in the last release? I see the image was updated 8 days ago.

**Comment by tsaridas** [comment]
> > which version of the container are you using ? can you post logs ?
> 
> I'm on the `:latest`, and it doesn't seem to have occurred in the last few days (also haven't really used it), maybe something was fixed in the last release? I see the image was updated 8 days ago.

can you try an older version ?

**Comment by tsaridas** [comment]
can you please check with :latest
