### ISSUE TITLE
Running in a Synology NAS

### ISSUE THREAD

**Issue by m4n0v31** [tsaridas/stremio-docker#39]
Hi,
was able to compile on a synology NAS (arch: appollolake) but I get the following when web interface connects to the server:
hls-converter - Tests for hardware accelerated transcoding finished, no viable acceleration profiles detected

I suspect, ffmpeg compilation didn't go well.
Is it possible to configure the docker in order to use ffmpeg binary which are already available on the synology NAS?
Or do you have any suggestion?

thank you

**Comment by tsaridas** [comment]
hi, 

you could try to mount the ffmpeg from the host to the docker container and change 
the following env variables

FFMPEG_BIN
FFPROBE_BIN

**Comment by m4n0v31** [comment]
Thx for the feedback, I actually solved, keeping the ffmpeg part unchanged by adding installation of following drivers (VAAPI) in the Dockerfile:
```
FROM base as final
RUN apk add --no-cache intel-media-driver
```
And mounting the device in the docker-compose:
```
devices:
      - "/dev/dri/card0:/dev/dri/card0"
      - "/dev/dri/renderD128:/dev/dri/renderD128"
```
HW accelerated transcoding is now available

**Comment by tsaridas** [comment]
that sounds great. I'll try to figure out how to add it as part of the amd64 image and add the devices part as part of the documentation. 
Thanks a lot for testing this.
