### ISSUE TITLE
New web version https://web.strem.io/ Server URL issue

### ISSUE THREAD

**Issue by asaddon** [tsaridas/stremio-docker#42]
Hello, for the newly released web version https://web.strem.io/ the query string to push server url is "streamingServerUrl" can you please add the funtionality to use this string if the URL "https://web.strem.io/ " is being used instead of the old version "https://app.strem.io/shell-v4.4/"

**Comment by tsaridas** [comment]
I do know that streamingServerUrl is added but I'm not sure what kind of functionality you expect from running the container.

**Comment by asaddon** [comment]
> I do know that streamingServerUrl is added but I'm not sure what kind of functionality you expect from running the container.

To use it to view on iOS and on the web.

**Comment by tsaridas** [comment]
I still don't understand what feature you would like me to add.

you can use streamingServerUrl with the current version of the container with something like :

```
http://192.168.1.10:8080/?streamingServerUrl=http%3A%2F%2F192.168.1.10%3A11470#/
```

**Comment by asaddon** [comment]
> I still don't understand what feature you would like me to add.
> 
> you can use streamingServerUrl with the current version of the container with something like :
> 
> ```
> http://192.168.1.10:8080/?streamingServerUrl=http%3A%2F%2F192.168.1.10%3A11470#/
> ```

I'm requesting you to add the functionality for "WEBUI_LOCATION" to handle "https://web.strem.io/" and "streamingServerUrl" redirect. "https://web.strem.io/" is mobile optimized and I can use it as a Web App on iOS, "app.strem.io" is not.

I unfortunately cannot use the local web player because I'm using Facebook login.

**Comment by asaddon** [comment]
Okay So I created an email account login to test the "https://web.strem.io/" functionality but It's giving me CORS error and not playing anything, I'm not sure if its something related to the new web.strem.io version or something else because even the local player is giving me same error.

Working fine with app.strem.io but its not mobile optimized :(

![Screenshot 2024-09-15 at 1 53 32 AM](https://github.com/user-attachments/assets/22c759e9-fb12-4754-b7af-cb5566f8c632)

**Comment by asaddon** [comment]
Not sure If I'm doing something wrong but I'm still seeing the same bahaviour.

**Comment by tsaridas** [comment]
Im not sure what you are doing wrong ><
the image works fine as far as I know.

**Comment by asaddon** [comment]
> Im not sure what you are doing wrong ><
> 
> the image works fine as far as I know.

web.strem.io endpoint is still not using the proper server url query endpoint, I'm currently out but I'll post a picture as well later.

**Comment by asaddon** [comment]
@tsaridas This is what I'm talking about, the current implementation of WEB UI add the extra parameter "streamingServer" in the URL which makes the link bad.

![Screenshot 2024-10-08 at 9 33 22 PM](https://github.com/user-attachments/assets/d533b509-8e1d-4b82-bc52-99c174822bd7)

**Comment by tsaridas** [comment]
I do not know .. I'm not from stremio. better go ask them in discord. I don't change their code

**Comment by asaddon** [comment]
> I do not know .. I'm not from stremio. better go ask them in discord. I don't change their code

Ah so this web ui redirection is from the stremio web code and not your implementation?

I apologize for the inconvenience then.
