### ISSUE TITLE
Wrap streamio in docker its more safe?

### ISSUE THREAD

**Issue by JuanjoOrt** [tsaridas/stremio-docker#46]
Hello,

More than a issue is it a question.

I used stremio in friends house a couple of times and it is great, but Im concerned about the security, at the end most of us gonna istall addons where they takes the torrent images from unknown places. I started this week doing virtual machines to wrap this app there and dont allow access to my real computer. but the performance is very low.

Im very very very new using docker, in fact I have to say that I haven't got any idea about it xd. Using docker images to wrap the stremio is going to give me the same secutiry as a cirtual machine??

Thanks in advance. have a good sunday

**Comment by tsaridas** [comment]
short answer(in my opinion) is no, containers are not safer than having them on a isolated VM. You can both make them to be more secure but in general there is not a huge different. One could also argue that escaping from the container to the host OS could be easier than escaping from a VM to the host.
it is safer than having stremio run directly on your laptop/pc OS where you store all your passwords etc. This is assuming some addon or something else in some way tries to do screechy things.
