### ISSUE TITLE
Server address resets every time you log out of the web UI

### ISSUE THREAD

**Issue by HVR88** [tsaridas/stremio-docker#47]
Every time you log out and back in to the webUI, the server settings is lost and reset back to 127.0.0.1 - it looks like the setting is stored in the browser's session cache.

Is there any way to set this permanently? Even better, to hard-code it into the docker config so that any time the web UI is loaded on any browser and any user logs in, my own server URL is always set up as default.

I'm OK with having to modify the original source code for Stremio to achieve this - I just need to know where to make the edit(s)

**Comment by tsaridas** [comment]
I do not know how to set this permanently. you can pass the server from url params 

```
http://stremio:8080/?streamingServerUrl=http://192.168.1.10:11470
```

**Comment by HVR88** [comment]
Thanks, that helps a lot. I'm able to use it with a bookmark to avoid having to re-enter the server. Good enough for now.

Tried to make it automatic using reverse proxy but wasn't able to make it work.
