### ISSUE TITLE
Stremio generates a huge amount of http request

### ISSUE THREAD

**Issue by jjftc** [tsaridas/stremio-docker#49]
Hi, I have been using this docker for some time and I am experiencing a strange error.

I can use stremio without any problem, but from time to time after a few hours or so, it starts doing a lot of requests to different trackers (announcements requests), including when I am not using the application 4 or 5 times per second.

To check if the problem is stremio itself or an add-on, I removed all the add-ons and the problem continues. 

Please, do you have any information about this issue?

**Comment by tsaridas** [comment]
its the stremio server (server.js). I have been struggling with it for some time. if you start the container and don't watch a movie it doesn't do anything but after watching a movie it opens the DHT server and never stops it. I have a cron restarting it every day but also a healthcheck script ([restart_if_idle.sh](https://github.com/tsaridas/stremio-docker/blob/main/restart_if_idle.sh)) that tries to see if anything is playing and kills the server if its not. sometimes it fails to recognize if something is playing and the spam to the dns continues. 
The trackers are hardcoded to server.js.

**Comment by jjftc** [comment]
Thanks for the response. I suspected the same thing. I will use the same approach as you. 

Thanks so much and congratulations for your work!!
