### ISSUE TITLE
is it possible to make this completely independent from stremio servers?

### ISSUE THREAD

**Issue by tubbadu** [tsaridas/stremio-docker#50]
I installed this in my server, but if I create an account for example it is not created on my server, but on stremio servers (in fact I can log in to the newly created account on https://web.stremio.com). 
how can I force it to never connect to the stremio server, and to keep all data locally on my server?

**Comment by tsaridas** [comment]
you would need to change https://github.com/Stremio/stremio-web

**Comment by tubbadu** [comment]
> you would need to change https://github.com/Stremio/stremio-web

thanks for the reply! Do you mean that it would be needed to fork stremio-web and modify it, or that this can be configured in stremio-web but it's not supported by stremio-docker?
