### ISSUE TITLE
Can I change default 8080 port?

### ISSUE THREAD

**Issue by puppinoo** [tsaridas/stremio-docker#53]
Trying to setup into a docker-compose with Gluetun VPN
https://github.com/qdm12/gluetun

Inside the same docker-compose I have another container which already uses 8080 port so if I add stremio-docker container it crashes saying the port is already in use.

Can I change it (external port is already changed, I probably need to change the internal one)?

Thanks

**Comment by tsaridas** [comment]
you should not and don't have to change the internal port. only external port.

**Comment by YarneThatsMe** [comment]
I have exactly the same issue, how does one change the external port in the unraid docker config? Changing the value of "Port*" from 8080 to something else doens't seem to work...
