### ISSUE TITLE
Cors error ("Video is not supported") when installed on VPS

### ISSUE THREAD

**Issue by puppinoo** [tsaridas/stremio-docker#54]
Hi,
Testing image.
So far so good but a few addons are not working cause they raise CORS exception when I use my local browser to connect to your remote web interface connected to your remote streaming server (not sure if this is the right way to use it but it works with many other addons).
I have NO_CORS=1 into docker compose.
You can test this issue installing an addon called USATV.
https://stremio-addons.netlify.app/usa-tv
This happens also with another addon called TorrentIo OffCloud and MediaFusion OffCloud but they required a paid subscription.
Thanks.

**Comment by tsaridas** [comment]
I'm using USATV locally without issues. If everything is HTTPS I don't think you need NO_CORS. 
what is the error you are getting exactly ?

**Comment by puppinoo** [comment]
Hi and thanks for help.
This is the error I receive.
The redacted url is my VPS address.
Basically I'm connecting to your docker web interface using my account from my local browser.
This morning I was able to open some url using app.strem.io but now I cant.
Maybe the issue is that I live in Italy and urls Im trying to open are georestricted.
My doubt is: when I try this setup (local browser in Italy -> remote web interface in US) The connection starts from Italy or US?
I'm not really sure.
Maybe it's an issue my side and not related to your app and I'm just wasting your time.

![image](https://github.com/user-attachments/assets/e5cbf5f3-f50c-4a5c-b68b-31bfc6cbeb61)

**Comment by puppinoo** [comment]
Ok, I was able to replay the issue.
If I use https://web.stremio.com/ WITHOUT connect to your streaming server on my US VPS I can open PBS Network channels.
If I connect stremio-docker streaming server to web.strem.io configuration it stops working.
I know its confusing but I hope you got it.
Basically if in the attached pic there is a ERROR it works.
If it says it's connected it doesnt.

![Schermata del 2024-11-20 18-50-18](https://github.com/user-attachments/assets/f1a9752a-6833-4841-8283-a9b06c135ae1)

**Comment by puppinoo** [comment]
Update
This is crazy.
If I use as url not https://<my.domain>:<port> BUT
https://my.domain:12470 it redirects to 
https://app.strem.io/shell-v4.4/?streamingServer=https%3A%2F%2F<<<my.domain>>>>%3A12470#/
This still has my remote streaming server connected and PBS works.

I have no idea why.

Thanks.

**Comment by tsaridas** [comment]
ah, now I remember. normal web player doesn't play TV channels but you can use the shell web player which is inside the docker container in url : https://<my.domain>:8080/shell/ and it should play TV channels. Try it out and let me know. As far as I know this is an issue with the beta web player.

**Comment by tsaridas** [comment]
transcoding needs hardware support. not sure what arch you are using. if its intel you can check the README to see what devices you need to present to the container for it to work.

**Comment by puppinoo** [comment]
My VPS is capable of Software transcoding.
Infact it work fine using Not live addons like Torrentio (RD or OC). YThe issue is only with Live TV.
For instance this addon alwasy gives me "Video is not supported". https://old.reddit.com/r/StremioAddons/comments/1e5mzed/mammamia_italian_https_addon/
Btw I bothered you even too much for today. Ill investigate better to understand if it's a local issue.


Thanks.

**Comment by tsaridas** [comment]
live TV doesn't need any server setup. Player directly plays the stream. if you want to use torrentio or other plugins that use the server you need to go to settings and setup server to your https://my.domain:12470 address.

**Comment by puppinoo** [comment]
Maybe you're right.
Maybe the error is unrelated to to streaming server.
The error is this
https://my.domain:12470/opensubHash?videoUrl=https%3A%2F%2Fd3749synfikwkv.cloudfront.net%2Fv1%2Fmaster%2F3722c60a815c199d9c0ef36c5b73da68a62b09d1%2Fcc-74ylxpgd78bpb%2FLive.m3u8
{"error":"response for calculating movie hash is wrong length: {\"start\":0,\"end\":65535} chunk_size 65536 but received 798"} so probably is related to opensubtitles plugin? I have to check better.

I have a custom script I created myself with limit acces to a whktelist of ips using ipset lists. Not perfect because Im not expert but it should do the job.

I use a VPS with these specs for 40$ / year
RAM: 4 GB
Disk: 60 GB
5TB quota / month
CPU: 4 Core(s) (AMD Ryzen 7950x).

**Comment by tsaridas** [comment]
> When from my Italy browser I open a stremio stream from https://my.domain:8080 which is not supported by the browser, streaming server kicks in and activate ffmpeg transcofing pipeline.

I'm not quite sure what you mean here. What exactly is not supported by your browser ? To open my.domain:8080 in https ? I don't see why.

pitty that nothing is exposed. I would imagine some extra packages would be required inside the docker container to support AMD HW transcoding and I don't have any devices to test ><

could you post an example of the docker compose together with the VPN? There are some users that want to do the same and it might be useful.

thanks!

**Comment by puppinoo** [comment]
> > When from my Italy browser I open a stremio stream from https://my.domain:8080 which is not supported by the browser, streaming server kicks in and activate ffmpeg transcofing pipeline.
> 


> I'm not quite sure what you mean here. What exactly is not supported by your browser ? To open my.domain:8080 in https ? I don't see why.
> 
This is what I understood (not sure if everything is right)
Browsers have limited codecs support. Video streams from RD or similar could be encoded using some unsupported CODECS (HEVC/H265 for 4k streams for example) so browser could open natively. If you have a streaming server configured in settings stremio web app (or native app) is smart enough to understand stream needs to be transcoded so sends the url to configured streaming server which launches in BG a ffmpeg command to transcode the stream in realtime and return it to your browser in compatible format (usually h264/aac).

> pitty that nothing is exposed. I would imagine some extra packages would be required inside the docker container to support AMD HW transcoding and I don't have any devices to test ><
> 
> could you post an example of the docker compose together with the VPN? There are some users that want to do the same and it might be useful.
> 
> thanks!

my docker-compose is a mess and could leak some personal info but you can check official Gluetun git repo for examples https://github.com/qdm12/gluetun

or some reddit group like this
https://old.reddit.com/r/selfhosted/comments/15oe631/gluetun_and_qbittorrent_correct_setup_in/

Gluetun is great cause its basically a VPN proxy into docker and you can tunnel others docker images through it.
with adding just a line like this to existing docker compose commands

network_mode: "service:gluetun"
so that docker will be automatically tunnelled through the VPN Gluetun is configured for.

Check the github and that example.

**Comment by puppinoo** [comment]
Basically we apparently have this problem
https://github.com/unalkalkan/stremio-docker-vpn

**Comment by puppinoo** [comment]
Yes, basically setting CASTING_DISABLED: 1 in image solved.
Ill have test better as soon as I come back from work.

**Comment by puppinoo** [comment]
Hi again,
Quick update about stremio-docker+ gluetun.
With CASTING_DISABLED:1 in dc no mor error and server starts

BUT (big one)

after that web interface using https://my.domain:8080 works but if I try setting https://my.domain:12470 into Settings -> Streaming server it gives error.
The only solution I found so far (quick attempt) is adding a sock5 into Gluetun docker-compose, install a sock5 addon called foxyproxy on my Mozilla firefox, configure it pointing to that sock5 on VPS and then once enabled open stremio web app and using as streaming serve http://127.0.0.1:11470

In that way it works streams work too (I tested a few RD ons)  except live streams.

But it faaar from practical.

Until I find a realwor (to me at least) solution Ill uso streamio docker outside Gluetun.

Sorry I wasnt more useful.

**Comment by puppinoo** [comment]
this is the config I tested if anyone want to test

``  stremio:
    image: tsaridas/stremio-docker:latest
    container_name: stremio-docker
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
    healthcheck:
      test: curl -sS http://localhost:11470/ || exit 1
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 20s
    environment:
      #NO_CORS: 1
      #IPADDRESS: {MY_PUBLIC_IP} # Setup your ip address here
      CERT_PATH: certificate.pem
      CASTING_DISABLED: 1
      DOMAIN: pinucc.io
#    ports:
#      - "8891:8080"
#      - "11470:11470" # Just one of the two should be enough
#      - "12470:12470"
    volumes:
      - "/root/.stremio-server:/root/.stremio-server" # set the first part to your local folder. Its not required though
    restart: unless-stopped ``

**Comment by puppinoo** [comment]
I chose the WORST moment to test this :D

**Comment by tsaridas** [comment]
> Hi again, Quick update about stremio-docker+ gluetun. With CASTING_DISABLED:1 in dockercompose no more error and server starts
> 
> BUT (big one)
> 
> after that web interface using https://my.domain:8080 works but if I try setting https://my.domain:12470 into Settings -> Streaming server it gives error (probably not reachable). The only solution I found so far (quick attempt) is adding a sock5 into Gluetun docker-compose, install a sock5 addon called foxyproxy on my Mozilla firefox, configure it pointing to that sock5 on VPS and then once enabled open stremio web app and using as streaming server http://127.0.0.1:11470
> 
> In that way it works streams work too (I tested a few RD ons) except live streams.
> 
> But it faaar from practical.
> 
> Until I find a realword (to me at least) solution Ill uso streamio docker outside Gluetun. Probably theres a variable (reading about a FIREWALL_OUTBOUND_SUBNETS ..but didnt get it) in gluetun setting or firewall config I ignore to make this work easily..
> 
> Sorry I wasnt more useful.

I'm guessing you are having the issues because of the VPN. I cannot help much there since I'm not using one. You would need to troubleshoot yourself. Happy to help but also hard to do so. You might need to forward some traffic not to go through VPN when its from your ip address.

**Comment by puppinoo** [comment]
Thanks,
I guess ill check vpn config. Also wrong time to test Debrid services right now.
I'll close issue.

Thanks.
