### ISSUE TITLE
Container memory usage - growing, leak ?

### ISSUE THREAD

**Issue by Saxin** [tsaridas/stremio-docker#56]
Hi @tsaridas, many thanks for putting this together.
Installed per your instructions on my MiniPC (Intel I3 5200U, 8Gb RAM and some storage), OS is Debian 11 (running headless)
PC mainly runs HA containers + serves SMB shares + some minor stuff.
After installing I've noticed that PC memory consumption goes up over time, below screenshot from HA host memory allocation monitoring, point (1) - Installed the STREMIO container, point (2) - roughly now - after ~20 hours. All that time no one used the new "toy", it was completely idle.

![image](https://github.com/user-attachments/assets/2851b92a-a1e5-4d09-b612-80f801268920)

Here is docker stats, it's now over time, but I've looked at it few times and I can see small change in stremio container over time with respect to memory.
![image](https://github.com/user-attachments/assets/604d0ba5-14cf-42cb-b3f4-6ca0b2ad66c4)

I would appreciate your feedback, notes, or maybe further steps I can do to isolate this issue. I'm complete noob in docker stuff so if something needed please guide me a bit.

Many thanks, Eddi

**Comment by tsaridas** [comment]
hi, 

software being bundled here is not written by myself. I do not know why it has such behaviour.

saying that, you can limit the container to specific memory or/and restart it periodically. 

I assume whats happening is that you watched a movie and that has been loaded in memory and/or some client is still connected to the server.

in my case I do see memory spike when watching/downloading a movie but then it goes down to normal limits (~256MB). I'm guessing you might have hit some exception or software doesn't release memory correctly which is not something i can help you with.
