### ISSUE TITLE
Change server port from 8080

### ISSUE THREAD

**Issue by matthew73210** [tsaridas/stremio-docker#57]
Hey,
Love this, works a charm. Running it through portainer as a stack with comet, zilean etc... on my home assistant server. The only issue is that one of my services already uses 8080. I've tried doing 8081:8080 but to no avail.
Any poss you could add an option to change ports? Might have miss understood your guide

**Comment by matthew73210** [comment]
Oh wait : 

  stremio:
    image: tsaridas/stremio-docker:latest
    container_name: stremio
    restart: unless-stopped
    environment:
      NO_CORS: 1
      # Uncomment and set IPADDRESS if necessary
      # IPADDRESS: 192.168.1.10
      WEBUI_LOCATION : http:0.0.0.0:8085
    ports:
      - "8085:8080"
      - "11470:11470" # You only need one of these ports open, adjust as needed
      - "12470:12470"
    volumes:
      - stremio_data:/root/.stremio-server  # Use Docker volume for persistence
    networks:
      - cometish  # Connect to the custom network

Should work right?

**Comment by matthew73210** [comment]
Tried that and it won't load the webpage

**Comment by tsaridas** [comment]
you cannot change the internal port but you can change the external port 

```
   ports:
     - "{this is the external port that you access the application from and is being forwarded to the internal port}:{This is the internal port that the application listens to}"
 ```

**Comment by iwconfig** [comment]
I'd like to change the internal port because I share network stack with another container with `network_mode: container:<container-name>` and port 8080 is used by another service.

Is it not possible to implement such a feature? I looked at `server-settings.json` but could not find anything obvious.
